# Generated by Django 5.0.8 on 2024-08-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='1,2,3,4,5,0,6,7,8,9,10', max_length=20)),
                ('moves', models.IntegerField(default=0)),
            ],
        ),
    ]
