# Generated by Django 5.0.8 on 2024-08-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='state',
            field=models.CharField(default='1,2,3,4,5,0,6,7,8,9,10', max_length=50),
        ),
    ]
