# Generated by Django 5.0.8 on 2024-08-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gamestate_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now=True)),
                ('registro', models.IntegerField()),
                ('uid', models.CharField(max_length=15)),
                ('intento', models.IntegerField()),
                ('movimiento', models.IntegerField()),
                ('trayectoria', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='GameState',
        ),
    ]
