# Generated by Django 5.0.8 on 2024-08-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_movimiento_delete_gamestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='trayectoria',
            field=models.CharField(max_length=50),
        ),
    ]
